# Generated by Django 4.2.7 on 2023-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endDate', models.DateField()),
                ('endTime', models.TimeField()),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
