# Generated by Django 5.0.1 on 2024-01-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeMaster', '0003_remove_student_email_alter_student_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contactNo',
            field=models.IntegerField(),
        ),
    ]
